// <auto-generated />
using Mango.Services.ProductAPI.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210609093325_SeedDataProduct")]
    partial class SeedDataProduct
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mango.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Shoes",
                            Description = "Hello world and hehe",
                            ImageUrl = "https://cf.shopee.vn/file/a7c893d688c8430db3f118c00319fc9a",
                            Name = "Shoes 1",
                            Price = 2000.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Shoes",
                            Description = "Hello world and hehe 222 ",
                            ImageUrl = "https://giayxshop.vn/wp-content/uploads/2021/01/z2261641090407_9a527dfa37fa44a1b8cfd0fd14d1ca77-scaled.jpg",
                            Name = "Shoes 2",
                            Price = 2000.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Ball",
                            Description = "Manchester United",
                            ImageUrl = "https://www.hidosport.com/uploads/5/4/1/0/54105107/manchester-united-18-19-home-kit-2-3_orig.jpg",
                            Name = "Ball hehe",
                            Price = 2000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
